[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pycoare"
version = "0.1"
requires-python = ">=3.7"
license = {text = "MIT License"}
dependencies = [
    "numpy"
]

[tool.setuptools.packages.find]
where = ["pycoare"]
include = [
    "coare3p5",
    "coare3p6"
]
namespaces = false
