name: Publish latest version to PyPi

on:
  push: 
    paths:
      - 'pyproject.toml'

jobs:
  build-n-publish:
    name: Build and publish latest version to PyPi
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
        shell: bash

      - name: Install pypa/build
      run: |
        python -m pip install build --user

      - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}